
services:
  # 1. NGINX Service (Single public entry point)
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure

  # 2. WordPress Service (PHP-FPM)
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
    secrets:
      - db_root_password
      - db_password

  # 3. MariaDB Service (Database)
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    secrets:
      - db_password 
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/h-el-ahr/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/h-el-ahr/data/mysql

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt