server{
    listen 443;
    server_name h-el-ahr.42.fr;

    ssl_protocols TLSv1.2 TLSv1.3;
    
    ssl_certificate     /etc/nginx/ssl/h-el-ahr.42.fr.crt;
    ssl_certificate_key /etc/nginx/ssl/h-el-ahr.42.fr.key;

}