workers_processes auto;

event{
    workers_connections 1024;
}

server{

    listen 443 ssl;
    server_name h-el-ahr.42.fr;

    ssl_protocols TLSv1.2 TLSv1.3;
    
    ssl_certificate     /etc/nginx/ssl/h-el-ahr.42.fr.crt;
    ssl_certificate_key /etc/nginx/ssl/h-el-ahr.42.fr.key;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        # fastcgi_bind 0.0.0.0.:
        fastcgi_pass wordpress:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
   
}
